language: python
python:
  - "3.7"
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - flake8 --exclude=venv* --statistics
  - pytest -v --cov-report term-missing --cov-report html:test-artifacts/cov_html --cov-report xml:test-reports/cov.xml --cov=main/ tests/
