# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - run: mkdir -p test-reports test-artifacts
      - run: which python
      # Step 2: create virtual env and install dependencies
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
          key: v2-dependencies-{{ checksum "requirements.txt" }}

      # Step 3: run linter and tests
      - run:
          name: run tests
          parallelism: 4
          command: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics
            pytest -v --cov-report term-missing --cov-report html:test-artifacts/cov_html --cov-report xml:test-reports/cov.xml --cov=main/ tests/
      - store_test_results:
          path: test-reports/  
      - store_artifacts:
          path: test-artifacts/
          destination: tr1